<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:47.
 */
class PHPMailerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPMailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPMailer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPMailer::IsHTML
     * @todo   Implement testIsHTML().
     */
    public function testIsHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsSMTP
     * @todo   Implement testIsSMTP().
     */
    public function testIsSMTP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsMail
     * @todo   Implement testIsMail().
     */
    public function testIsMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsSendmail
     * @todo   Implement testIsSendmail().
     */
    public function testIsSendmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsQmail
     * @todo   Implement testIsQmail().
     */
    public function testIsQmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddAddress
     * @todo   Implement testAddAddress().
     */
    public function testAddAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddCC
     * @todo   Implement testAddCC().
     */
    public function testAddCC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddBCC
     * @todo   Implement testAddBCC().
     */
    public function testAddBCC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddReplyTo
     * @todo   Implement testAddReplyTo().
     */
    public function testAddReplyTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetFrom
     * @todo   Implement testSetFrom().
     */
    public function testSetFrom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ValidateAddress
     * @todo   Implement testValidateAddress().
     */
    public function testValidateAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::Send
     * @todo   Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SmtpConnect
     * @todo   Implement testSmtpConnect().
     */
    public function testSmtpConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SmtpClose
     * @todo   Implement testSmtpClose().
     */
    public function testSmtpClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetLanguage
     * @todo   Implement testSetLanguage().
     */
    public function testSetLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::GetTranslations
     * @todo   Implement testGetTranslations().
     */
    public function testGetTranslations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddrAppend
     * @todo   Implement testAddrAppend().
     */
    public function testAddrAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddrFormat
     * @todo   Implement testAddrFormat().
     */
    public function testAddrFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::WrapText
     * @todo   Implement testWrapText().
     */
    public function testWrapText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::UTF8CharBoundary
     * @todo   Implement testUTF8CharBoundary().
     */
    public function testUTF8CharBoundary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetWordWrap
     * @todo   Implement testSetWordWrap().
     */
    public function testSetWordWrap() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::CreateHeader
     * @todo   Implement testCreateHeader().
     */
    public function testCreateHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::GetMailMIME
     * @todo   Implement testGetMailMIME().
     */
    public function testGetMailMIME() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::CreateBody
     * @todo   Implement testCreateBody().
     */
    public function testCreateBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::HeaderLine
     * @todo   Implement testHeaderLine().
     */
    public function testHeaderLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::TextLine
     * @todo   Implement testTextLine().
     */
    public function testTextLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::GetAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeString
     * @todo   Implement testEncodeString().
     */
    public function testEncodeString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeHeader
     * @todo   Implement testEncodeHeader().
     */
    public function testEncodeHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::HasMultiBytes
     * @todo   Implement testHasMultiBytes().
     */
    public function testHasMultiBytes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::Base64EncodeWrapMB
     * @todo   Implement testBase64EncodeWrapMB().
     */
    public function testBase64EncodeWrapMB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeQPphp
     * @todo   Implement testEncodeQPphp().
     */
    public function testEncodeQPphp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeQP
     * @todo   Implement testEncodeQP().
     */
    public function testEncodeQP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeQ
     * @todo   Implement testEncodeQ().
     */
    public function testEncodeQ() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddStringAttachment
     * @todo   Implement testAddStringAttachment().
     */
    public function testAddStringAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddEmbeddedImage
     * @todo   Implement testAddEmbeddedImage().
     */
    public function testAddEmbeddedImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::InlineImageExists
     * @todo   Implement testInlineImageExists().
     */
    public function testInlineImageExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAddresses
     * @todo   Implement testClearAddresses().
     */
    public function testClearAddresses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearCCs
     * @todo   Implement testClearCCs().
     */
    public function testClearCCs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearBCCs
     * @todo   Implement testClearBCCs().
     */
    public function testClearBCCs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearReplyTos
     * @todo   Implement testClearReplyTos().
     */
    public function testClearReplyTos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAllRecipients
     * @todo   Implement testClearAllRecipients().
     */
    public function testClearAllRecipients() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAttachments
     * @todo   Implement testClearAttachments().
     */
    public function testClearAttachments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearCustomHeaders
     * @todo   Implement testClearCustomHeaders().
     */
    public function testClearCustomHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::RFCDate
     * @todo   Implement testRFCDate().
     */
    public function testRFCDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsError
     * @todo   Implement testIsError().
     */
    public function testIsError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddCustomHeader
     * @todo   Implement testAddCustomHeader().
     */
    public function testAddCustomHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::MsgHTML
     * @todo   Implement testMsgHTML().
     */
    public function testMsgHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::_mime_types
     * @todo   Implement test_mime_types().
     */
    public function test_mime_types() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SecureHeader
     * @todo   Implement testSecureHeader().
     */
    public function testSecureHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::Sign
     * @todo   Implement testSign().
     */
    public function testSign() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::DKIM_QP
     * @todo   Implement testDKIM_QP().
     */
    public function testDKIM_QP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::DKIM_Sign
     * @todo   Implement testDKIM_Sign().
     */
    public function testDKIM_Sign() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::DKIM_HeaderC
     * @todo   Implement testDKIM_HeaderC().
     */
    public function testDKIM_HeaderC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::DKIM_BodyC
     * @todo   Implement testDKIM_BodyC().
     */
    public function testDKIM_BodyC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::DKIM_Add
     * @todo   Implement testDKIM_Add().
     */
    public function testDKIM_Add() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
