<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:44.
 */
class IMAPMAILTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IMAPMAIL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IMAPMAIL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers IMAPMAIL::set_host
     * @todo   Implement testSet_host().
     */
    public function testSet_host() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::set_port
     * @todo   Implement testSet_port().
     */
    public function testSet_port() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_error
     * @todo   Implement testGet_error().
     */
    public function testGet_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_state
     * @todo   Implement testGet_state().
     */
    public function testGet_state() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::open_mailbox
     * @todo   Implement testOpen_mailbox().
     */
    public function testOpen_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_unseen_msglist
     * @todo   Implement testGet_unseen_msglist().
     */
    public function testGet_unseen_msglist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_recent_msglist
     * @todo   Implement testGet_recent_msglist().
     */
    public function testGet_recent_msglist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_msglist
     * @todo   Implement testGet_msglist().
     */
    public function testGet_msglist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_list
     * @todo   Implement testGet_list().
     */
    public function testGet_list() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_message_body
     * @todo   Implement testGet_message_body().
     */
    public function testGet_message_body() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_message_header
     * @todo   Implement testGet_message_header().
     */
    public function testGet_message_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_message
     * @todo   Implement testGet_message().
     */
    public function testGet_message() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::delete_message
     * @todo   Implement testDelete_message().
     */
    public function testDelete_message() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::rollback_delete
     * @todo   Implement testRollback_delete().
     */
    public function testRollback_delete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_line
     * @todo   Implement testGet_line().
     */
    public function testGet_line() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_server_responce
     * @todo   Implement testGet_server_responce().
     */
    public function testGet_server_responce() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::put_line
     * @todo   Implement testPut_line().
     */
    public function testPut_line() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::open_connection
     * @todo   Implement testOpen_connection().
     */
    public function testOpen_connection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_capability
     * @todo   Implement testGet_capability().
     */
    public function testGet_capability() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::noop
     * @todo   Implement testNoop().
     */
    public function testNoop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::select_mailbox
     * @todo   Implement testSelect_mailbox().
     */
    public function testSelect_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::examin_mailbox
     * @todo   Implement testExamin_mailbox().
     */
    public function testExamin_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::create_mailbox
     * @todo   Implement testCreate_mailbox().
     */
    public function testCreate_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::delete_mailbox
     * @todo   Implement testDelete_mailbox().
     */
    public function testDelete_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::rename_mailbox
     * @todo   Implement testRename_mailbox().
     */
    public function testRename_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::subscribe_mailbox
     * @todo   Implement testSubscribe_mailbox().
     */
    public function testSubscribe_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::unsubscribe_mailbox
     * @todo   Implement testUnsubscribe_mailbox().
     */
    public function testUnsubscribe_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::list_mailbox
     * @todo   Implement testList_mailbox().
     */
    public function testList_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::list_subscribed_mailbox
     * @todo   Implement testList_subscribed_mailbox().
     */
    public function testList_subscribed_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::get_status
     * @todo   Implement testGet_status().
     */
    public function testGet_status() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::check_mailbox
     * @todo   Implement testCheck_mailbox().
     */
    public function testCheck_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::close_mailbox
     * @todo   Implement testClose_mailbox().
     */
    public function testClose_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::expunge_mailbox
     * @todo   Implement testExpunge_mailbox().
     */
    public function testExpunge_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::search_mailbox
     * @todo   Implement testSearch_mailbox().
     */
    public function testSearch_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::uid_search_mailbox
     * @todo   Implement testUid_search_mailbox().
     */
    public function testUid_search_mailbox() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::fetch_mail
     * @todo   Implement testFetch_mail().
     */
    public function testFetch_mail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::uid_fetch_mail
     * @todo   Implement testUid_fetch_mail().
     */
    public function testUid_fetch_mail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::store_mail_flag
     * @todo   Implement testStore_mail_flag().
     */
    public function testStore_mail_flag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::uid_store_mail_flag
     * @todo   Implement testUid_store_mail_flag().
     */
    public function testUid_store_mail_flag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::copy_mail
     * @todo   Implement testCopy_mail().
     */
    public function testCopy_mail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers IMAPMAIL::uid_copy_mail
     * @todo   Implement testUid_copy_mail().
     */
    public function testUid_copy_mail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
