<?php
namespace SendGrid;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:16:26.
 */
class EmailTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Email
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Email;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SendGrid\Email::addTo
     * @todo   Implement testAddTo().
     */
    public function testAddTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setTos
     * @todo   Implement testSetTos().
     */
    public function testSetTos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setFrom
     * @todo   Implement testSetFrom().
     */
    public function testSetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getFrom
     * @todo   Implement testGetFrom().
     */
    public function testGetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setFromName
     * @todo   Implement testSetFromName().
     */
    public function testSetFromName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getFromName
     * @todo   Implement testGetFromName().
     */
    public function testGetFromName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setReplyTo
     * @todo   Implement testSetReplyTo().
     */
    public function testSetReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getReplyTo
     * @todo   Implement testGetReplyTo().
     */
    public function testGetReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setCc
     * @todo   Implement testSetCc().
     */
    public function testSetCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setCcs
     * @todo   Implement testSetCcs().
     */
    public function testSetCcs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addCc
     * @todo   Implement testAddCc().
     */
    public function testAddCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::removeCc
     * @todo   Implement testRemoveCc().
     */
    public function testRemoveCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getCcs
     * @todo   Implement testGetCcs().
     */
    public function testGetCcs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setBcc
     * @todo   Implement testSetBcc().
     */
    public function testSetBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setBccs
     * @todo   Implement testSetBccs().
     */
    public function testSetBccs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addBcc
     * @todo   Implement testAddBcc().
     */
    public function testAddBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::removeBcc
     * @todo   Implement testRemoveBcc().
     */
    public function testRemoveBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getBccs
     * @todo   Implement testGetBccs().
     */
    public function testGetBccs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setText
     * @todo   Implement testSetText().
     */
    public function testSetText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getText
     * @todo   Implement testGetText().
     */
    public function testGetText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setHtml
     * @todo   Implement testSetHtml().
     */
    public function testSetHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getHtml
     * @todo   Implement testGetHtml().
     */
    public function testGetHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setAttachments
     * @todo   Implement testSetAttachments().
     */
    public function testSetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setAttachment
     * @todo   Implement testSetAttachment().
     */
    public function testSetAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::removeAttachment
     * @todo   Implement testRemoveAttachment().
     */
    public function testRemoveAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setCategories
     * @todo   Implement testSetCategories().
     */
    public function testSetCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setCategory
     * @todo   Implement testSetCategory().
     */
    public function testSetCategory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addCategory
     * @todo   Implement testAddCategory().
     */
    public function testAddCategory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::removeCategory
     * @todo   Implement testRemoveCategory().
     */
    public function testRemoveCategory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setSubstitutions
     * @todo   Implement testSetSubstitutions().
     */
    public function testSetSubstitutions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addSubstitution
     * @todo   Implement testAddSubstitution().
     */
    public function testAddSubstitution()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setSections
     * @todo   Implement testSetSections().
     */
    public function testSetSections()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addSection
     * @todo   Implement testAddSection().
     */
    public function testAddSection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setUniqueArgs
     * @todo   Implement testSetUniqueArgs().
     */
    public function testSetUniqueArgs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setUniqueArguments
     * @todo   Implement testSetUniqueArguments().
     */
    public function testSetUniqueArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addUniqueArg
     * @todo   Implement testAddUniqueArg().
     */
    public function testAddUniqueArg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addUniqueArgument
     * @todo   Implement testAddUniqueArgument().
     */
    public function testAddUniqueArgument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setFilters
     * @todo   Implement testSetFilters().
     */
    public function testSetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setFilterSettings
     * @todo   Implement testSetFilterSettings().
     */
    public function testSetFilterSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addFilter
     * @todo   Implement testAddFilter().
     */
    public function testAddFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addFilterSetting
     * @todo   Implement testAddFilterSetting().
     */
    public function testAddFilterSetting()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getHeaders
     * @todo   Implement testGetHeaders().
     */
    public function testGetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::getHeadersJson
     * @todo   Implement testGetHeadersJson().
     */
    public function testGetHeadersJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::setHeaders
     * @todo   Implement testSetHeaders().
     */
    public function testSetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::addHeader
     * @todo   Implement testAddHeader().
     */
    public function testAddHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::removeHeader
     * @todo   Implement testRemoveHeader().
     */
    public function testRemoveHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::toWebFormat
     * @todo   Implement testToWebFormat().
     */
    public function testToWebFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SendGrid\Email::updateMissingTo
     * @todo   Implement testUpdateMissingTo().
     */
    public function testUpdateMissingTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
